name: Issue Report
description: File an Issue
title: "[Problem]: "
labels: ["new issue"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: version
    attributes:
      label: Configuration Information.
      description: Please paste the results of `shairport-sync --displayConfig` here, if available. This gives useful information about the environment Shairport Sync is running in and also displays the command line options and configuration settings. If `shairport-sync --displayConfig` is not available (it's new), please paste the results of two commands: `uname -a` and  `shairport-sync -V`.
    validations:
      required: true
  - type: dropdown
    id: install
    attributes:
      label: How did you install Shairport Sync?
      options:
        - Homebrew for Mac
        - Docker
        - A package manager (apt, apt install, yum, pkg, etc.)
        - Built from source
    validations:
      required: true
  - type: checkboxes
    id: checked-current-issues
    attributes:
      label: Check previous issues
      description: Please check previous issues (including closed ones) for duplicates.
      options:
        - label: Confirm
          required: true

