<<<<<<< HEAD
name: Issue Report
description: File an Issue
title: "[Problem]: "
labels: ["new issue"]
=======
name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
>>>>>>> origin/development
body:
  - type: markdown
    attributes:
      value: |
<<<<<<< HEAD
        Thanks for taking the time to fill out this report!
=======
        Thanks for taking the time to fill out this bug report!
>>>>>>> origin/development
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
<<<<<<< HEAD
    id: os
    attributes:
      label: Operating System?
      description: What Operating System are you running on ? (`uname -a`)
    validations:
      required: true
  - type: textarea
=======
>>>>>>> origin/development
    id: version
    attributes:
      label: Version?
      description: What version of Shairport Sync are you running? (`shairport-sync -V`)
    validations:
      required: true
<<<<<<< HEAD
  - type: dropdown
    id: install
    attributes:
      label: How did you install Shairport Sync?
      options:
        - Homebrew for Mac
        - Docker
        - A package manager (apt, yum, pkg, etc.)
        - Built from source
    validations:
      required: true
=======
>>>>>>> origin/development
  - type: checkboxes
    id: checked-current-issues
    attributes:
      label: Check previous issues
      description: Please check previous issues (including closed ones) for duplicates.
      options:
        - label: Confirm
<<<<<<< HEAD
          required: true
=======
          required: true
>>>>>>> origin/development
