name: Issue Report
description: File an Issue
title: "[Problem]: "
labels: ["troubleshooting"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: os
    attributes:
      label: Operating System?
      description: Please tell us what Operating System are you running on. (`$ uname -a`)
  - type: textarea
    id: version
    attributes:
      label: Version?
      description: Please tell us what version of Shairport Sync are you running. (`$ shairport-sync -V`)
    validations:
      required: true
  body:
- type: dropdown
  id: download
  attributes:
    label: How did you install Shairport Sync?
    options:
      - A Package Manager, e.g. `apt`, `yum`, `pkg`, ...
      - Homebrew for Mac
      - Built from source
  validations:
    required: true
- type: checkboxes
    id: checked-current-issues
    attributes:
      label: Check previous issues
      description: Please check previous issues (including closed ones) for duplicates.
      options:
        - label: Confirm
          required: true
