blank_issues_enabled: false
contact_links:
  - name: Questions?
    url: https://github.com/mikebrady/shairport-sync/discussions/categories/q-a
    about: Please ask and answer questions here.
  - name: Feature Requests
    url: https://github.com/mikebrady/shairport-sync/discussions/categories/ideas
    about: Please submit feature requests/enhancements here.