# Example docker compose config.

services:
  shairport-sync:
    image: registry.nova.do/shairport-sync:unstable-development
    network_mode: host
    restart: unless-stopped
    devices:
      - "/dev/snd"
    # volumes:
    #   - ./volumes/shairport-sync/shairport-sync.conf:/etc/shairport-sync.conf # Customised Shairport Sync configuration file.