name: Check Basic Classic on macOS with brew

on:
  push:
    branches: [ "danger" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        brew update
        brew install automake
        brew install openssl
        brew upgrade

    - name: Set Equates
      run: |
        export CPPFLAGS="-I/usr/local/opt/openssl@3/include"
        export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
        export PATH="$(brew --prefix)/opt/openssl/bin:${PATH}"
        export PKG_CONFIG_PATH="$(brew --prefix)/opt/openssl/lib/pkgconfig"

    - name: Configure
      run: |
        autoreconf -fi
        ./configure --with-os=darwin --with-ao --with-stdout --with-dns_sd --with-ssl=openssl
    
    - name: Make
      run: |
        make
