# Pushes to tag 'unstable' since it uses the master branch directly.
# Releases are pushed to latest and tagged - see docker-build-releases.yaml.

name: Build and push docker image based on master branch.

on:
  push:
    branches: [ master, development ]
 
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set branch env.
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: registry.nova.do
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm64,linux/arm/v7
          push: true
          tags: registry.nova.do/shairport-sync:unstable-${{ env.BRANCH }}
          build-args: |
            BRANCH=${{ env.BRANCH }}
          ssh: [ ${{ secrets.SSH_PRIVATE_KEY }} ]