# Builds & pushes a docker image when a release occurs.

# The following tags are created:
# 'latest' & 'latest-airplay1'
# '[RELEASE TAG]' & '[RELEASE TAG]-airplay1'

name: Build and push docker images on releases.

on:
  release:
    types: [ ]
 
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Set SHAIRPORT_SYNC_BRANCH env.
        run: echo "SHAIRPORT_SYNC_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Determine NQPTP env (part 1).
        if: env.SHAIRPORT_SYNC_BRANCH == 'development'
        run: echo "NQPTP_BRANCH=development" >> $GITHUB_ENV
      
      - name: Determine NQPTP env (part 2).
        if: env.SHAIRPORT_SYNC_BRANCH != 'development'
        run: echo "NQPTP_BRANCH=master" >> $GITHUB_ENV
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/shairport-sync:latest ${{ secrets.DOCKER_REGISTRY }}/shairport-sync:${{ github.event.release.tag_name }}
          build-args: |
            SHAIRPORT_SYNC_BRANCH=${{ env.SHAIRPORT_SYNC_BRANCH }}

      - name: Build and push (AirPlay 1)
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/airplay1/Dockerfile-AirPlay1
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/shairport-sync:latest-airplay1, ${{ secrets.DOCKER_REGISTRY }}/shairport-sync:${{ github.event.release.tag_name }}-airplay1
          build-args: |
            SHAIRPORT_SYNC_BRANCH=${{ env.SHAIRPORT_SYNC_BRANCH }}